#!/usr/bin/env python3
"""
Integration tests for docs/render-md.py.

Feeds the zustand investigation form fixture through the renderer and asserts
the structure matches the golden docs/GitHub-Scanner-zustand.md. Section-level
assertions (not full diff-match) so we can extend the fixture incrementally
without breaking every test.

Run: python3 -m pytest tests/test_render_md.py -v
"""

import importlib.util
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent

# render-md.py has a hyphen, so import via importlib.
_spec = importlib.util.spec_from_file_location("render_md", REPO_ROOT / "docs" / "render-md.py")
_render_md = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_render_md)
render = _render_md.render


FIXTURE = REPO_ROOT / "tests" / "fixtures" / "zustand-form.json"
GOLDEN = REPO_ROOT / "docs" / "GitHub-Scanner-zustand.md"


def load_form():
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def rendered():
    return render(load_form())


# ---------------------------------------------------------------------------
# Structural: sections rendered from fixture data
# ---------------------------------------------------------------------------

class TestStructuralSections:

    def test_has_title(self):
        out = rendered()
        assert out.startswith("# Security Investigation: pmndrs/zustand")

    def test_has_caption(self):
        out = rendered()
        assert "> A 57,000-star React state library" in out

    def test_has_catalog_section(self):
        assert "## Catalog metadata" in rendered()

    def test_has_verdict_section(self):
        out = rendered()
        assert "## Verdict: Caution" in out
        assert "Deployment axis" in out

    def test_has_scorecard_section(self):
        assert "## Trust Scorecard" in rendered()

    def test_has_section_01(self):
        assert "## 01 · What should I do?" in rendered()

    def test_has_section_02(self):
        assert "## 02 · What we found" in rendered()

    def test_has_section_03(self):
        assert "## 03 · Suspicious code changes" in rendered()

    def test_has_section_04(self):
        assert "## 04 · Timeline" in rendered()

    def test_has_section_08(self):
        assert "## 08 · How this scan works" in rendered()

    def test_has_footer(self):
        assert "*Generated by [stop-git-std]" in rendered()


# ---------------------------------------------------------------------------
# Facts: key data from the form surfaces correctly in the output
# ---------------------------------------------------------------------------

class TestFacts:

    def test_head_sha_present(self):
        out = rendered()
        assert "32013285083648e8d58ba1f76d73b9bdc02fef50" in out

    def test_latest_release_tag_present(self):
        assert "v5.0.12" in rendered()

    def test_verdict_level_matches_phase_4b(self):
        form = load_form()
        expected_level = form["phase_4b_computed"]["verdict"]["level"]
        out = rendered()
        # Verdict appears in catalog row AND verdict header
        assert expected_level in out

    def test_all_findings_appear(self):
        form = load_form()
        out = rendered()
        for f in form["phase_4_structured_llm"]["findings"]["entries"]:
            assert f["id"] in out, f"Finding {f['id']} missing from output"
            assert f["title"] in out, f"Title of {f['id']} missing"

    def test_finding_severities_rendered(self):
        out = rendered()
        # F0 is Warning + Structural + boundary case → all three in header
        assert "F0 — Warning · Structural · boundary case" in out

    def test_scorecard_colors_match_computed(self):
        form = load_form()
        out = rendered()
        cells = form["phase_3_computed"]["scorecard_cells"]
        # Q1 is amber → ⚠ icon
        # Q2, Q3, Q4 are green → ✅ icon
        assert cells["does_anyone_check_the_code"]["color"] == "amber"
        assert "| Does anyone check the code? | ⚠" in out
        assert "| Is it safe out of the box? | ✅" in out
        assert "| Do they fix problems quickly? | ✅" in out
        assert "| Do they tell you about problems? | ✅" in out

    def test_action_step_count(self):
        form = load_form()
        out = rendered()
        for s in form["phase_4_structured_llm"]["action_steps"]["entries"]:
            assert f"### Step {s['step']}" in out

    def test_timeline_events_rendered(self):
        form = load_form()
        out = rendered()
        for e in form["phase_4_structured_llm"]["timeline_events"]["entries"]:
            assert e["date"] in out
            assert e["label"] in out


# ---------------------------------------------------------------------------
# Formatting: markdown patterns match golden style
# ---------------------------------------------------------------------------

class TestFormatting:

    def test_section_summary_blockquotes(self):
        """Sections should open with a `> summary` blockquote."""
        out = rendered()
        # Section 01 has a blockquote summary
        m = re.search(r"## 01 · What should I do\?\n\n> ", out)
        assert m is not None, "Section 01 missing blockquote summary"

    def test_scorecard_question_order_matches_golden(self):
        out = rendered()
        golden = GOLDEN.read_text(encoding="utf-8")
        # Extract the scorecard question column order from both
        def extract_questions(text):
            block = re.search(
                r"## Trust Scorecard.*?\n\n(.*?)\n---",
                text,
                flags=re.DOTALL,
            )
            if not block:
                return []
            return re.findall(r"\| ([^|]+\?) \|", block.group(1))
        assert extract_questions(out) == extract_questions(golden)

    def test_finding_prose_paragraphs_rendered(self):
        """Findings with per_finding_prose get the 'what this means' paragraph."""
        out = rendered()
        # F0 has prose in the fixture
        assert "**What this means for you.**" in out
        assert "**What this does NOT mean.**" in out

    def test_horizontal_rules_between_sections(self):
        """Each major section should be separated by `---` rules."""
        out = rendered()
        assert out.count("\n---\n") >= 8

    def test_no_unrendered_template_tokens(self):
        """Output must not contain unfilled `{{ }}` placeholders."""
        out = rendered()
        assert "{{" not in out
        assert "}}" not in out


# ---------------------------------------------------------------------------
# Graceful degradation: sections without data don't break the render
# ---------------------------------------------------------------------------

class TestGracefulDegradation:

    def test_missing_evidence_skips_section_07(self):
        """Fixture has no evidence.entries → section 07 omitted, no crash."""
        out = rendered()
        # Since fixture has no evidence.entries, section 07 should be absent
        # (this will change once the fixture is enriched — test then flips)
        form = load_form()
        has_evidence = bool(form["phase_4_structured_llm"].get("evidence", {}).get("entries"))
        if has_evidence:
            assert "## 07 · Evidence appendix" in out
        else:
            assert "## 07 · Evidence appendix" not in out

    def test_missing_coverage_cells_skips_section_06(self):
        form = load_form()
        out = rendered()
        has_coverage = (
            bool(form["phase_3_computed"].get("coverage_status", {}).get("cells"))
            or bool(form["phase_4_structured_llm"].get("coverage_detail", {}).get("rows"))
        )
        if has_coverage:
            assert "## 06 · Investigation coverage" in out
        else:
            assert "## 06 · Investigation coverage" not in out


if __name__ == "__main__":
    import pytest
    sys.exit(pytest.main([__file__, "-v"]))
