#!/usr/bin/env python3
"""
Integration tests for docs/render-md.py.

Feeds the zustand investigation form fixture through the renderer and asserts
the structure matches the golden docs/scans/catalog/GitHub-Scanner-zustand.md.
Section-level assertions (not full diff-match) so we can extend the fixture
incrementally without breaking every test.

Run: python3 -m pytest tests/test_render_md.py -v
"""

import importlib.util
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent

# render-md.py has a hyphen, so import via importlib.
_spec = importlib.util.spec_from_file_location("render_md", REPO_ROOT / "docs" / "render-md.py")
_render_md = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_render_md)
render = _render_md.render


FIXTURE = REPO_ROOT / "tests" / "fixtures" / "zustand-form.json"
GOLDEN = REPO_ROOT / "docs" / "scans" / "catalog" / "GitHub-Scanner-zustand.md"


def load_form():
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def rendered():
    return render(load_form())


# ---------------------------------------------------------------------------
# Structural: sections rendered from fixture data
# ---------------------------------------------------------------------------

class TestStructuralSections:

    def test_has_title(self):
        out = rendered()
        assert out.startswith("# Security Investigation: pmndrs/zustand")

    def test_has_caption(self):
        out = rendered()
        assert "> A 57,000-star React state library" in out

    def test_has_catalog_section(self):
        assert "## Catalog metadata" in rendered()

    def test_has_verdict_section(self):
        out = rendered()
        assert "## Verdict: Caution" in out
        assert "Deployment axis" in out

    def test_has_scorecard_section(self):
        assert "## Trust Scorecard" in rendered()

    def test_has_section_01(self):
        assert "## 01 · What should I do?" in rendered()

    def test_has_section_02(self):
        assert "## 02 · What we found" in rendered()

    def test_has_section_03(self):
        assert "## 03 · Suspicious code changes" in rendered()

    def test_has_section_04(self):
        assert "## 04 · Timeline" in rendered()

    def test_has_section_08(self):
        assert "## 08 · How this scan works" in rendered()

    def test_has_footer(self):
        assert "*Generated by [stop-git-std]" in rendered()


# ---------------------------------------------------------------------------
# Facts: key data from the form surfaces correctly in the output
# ---------------------------------------------------------------------------

class TestFacts:

    def test_head_sha_present(self):
        out = rendered()
        assert "32013285083648e8d58ba1f76d73b9bdc02fef50" in out

    def test_latest_release_tag_present(self):
        assert "v5.0.12" in rendered()

    def test_verdict_level_matches_phase_4b(self):
        form = load_form()
        expected_level = form["phase_4b_computed"]["verdict"]["level"]
        out = rendered()
        # Verdict appears in catalog row AND verdict header
        assert expected_level in out

    def test_all_findings_appear(self):
        form = load_form()
        out = rendered()
        for f in form["phase_4_structured_llm"]["findings"]["entries"]:
            assert f["id"] in out, f"Finding {f['id']} missing from output"
            assert f["title"] in out, f"Title of {f['id']} missing"

    def test_finding_severities_rendered(self):
        out = rendered()
        # F0 is Warning + Structural + boundary case → all three in header
        assert "F0 — Warning · Structural · boundary case" in out

    def test_scorecard_colors_match_computed(self):
        form = load_form()
        out = rendered()
        # V1.2 D2: scorecard authority moved to phase_4_structured_llm
        cells = form["phase_4_structured_llm"]["scorecard_cells"]
        # Q1 is amber → ⚠ icon
        # Q2, Q3, Q4 are green → ✅ icon
        assert cells["does_anyone_check_the_code"]["color"] == "amber"
        assert "| Does anyone check the code? | ⚠" in out
        assert "| Is it safe out of the box? | ✅" in out
        assert "| Do they fix problems quickly? | ✅" in out
        assert "| Do they tell you about problems? | ✅" in out

    def test_scorecard_cells_live_in_phase_4_not_phase_3(self):
        """V1.2 D2 invariant: scorecard authority is phase_4_structured_llm.
        phase_3_computed must no longer carry scorecard_cells."""
        form = load_form()
        assert "scorecard_cells" in form["phase_4_structured_llm"]
        assert "scorecard_cells" not in form.get("phase_3_computed", {})

    def test_phase_3_advisory_present_on_v12_fixture(self):
        """V1.2 fixtures must have phase_3_advisory.scorecard_hints populated."""
        form = load_form()
        assert "phase_3_advisory" in form
        hints = form["phase_3_advisory"]["scorecard_hints"]
        for q in ("does_anyone_check_the_code", "do_they_fix_problems_quickly",
                  "do_they_tell_you_about_problems", "is_it_safe_out_of_the_box"):
            assert q in hints, f"missing advisory hint for {q}"

    def test_action_step_count(self):
        form = load_form()
        out = rendered()
        for s in form["phase_4_structured_llm"]["action_steps"]["entries"]:
            assert f"### Step {s['step']}" in out

    def test_timeline_events_rendered(self):
        form = load_form()
        out = rendered()
        for e in form["phase_4_structured_llm"]["timeline_events"]["entries"]:
            assert e["date"] in out
            assert e["label"] in out


# ---------------------------------------------------------------------------
# Formatting: markdown patterns match golden style
# ---------------------------------------------------------------------------

class TestFormatting:

    def test_section_summary_blockquotes(self):
        """Sections should open with a `> summary` blockquote."""
        out = rendered()
        # Section 01 has a blockquote summary
        m = re.search(r"## 01 · What should I do\?\n\n> ", out)
        assert m is not None, "Section 01 missing blockquote summary"

    def test_scorecard_question_order_matches_golden(self):
        out = rendered()
        golden = GOLDEN.read_text(encoding="utf-8")
        # Extract the scorecard question column order from both
        def extract_questions(text):
            block = re.search(
                r"## Trust Scorecard.*?\n\n(.*?)\n---",
                text,
                flags=re.DOTALL,
            )
            if not block:
                return []
            return re.findall(r"\| ([^|]+\?) \|", block.group(1))
        assert extract_questions(out) == extract_questions(golden)

    def test_finding_prose_paragraphs_rendered(self):
        """Findings with per_finding_prose get the 'what this means' paragraph."""
        out = rendered()
        # F0 has prose in the fixture
        assert "**What this means for you.**" in out
        assert "**What this does NOT mean.**" in out

    def test_horizontal_rules_between_sections(self):
        """Each major section should be separated by `---` rules."""
        out = rendered()
        assert out.count("\n---\n") >= 8

    def test_no_unrendered_template_tokens(self):
        """Output must not contain unfilled `{{ }}` placeholders."""
        out = rendered()
        assert "{{" not in out
        assert "}}" not in out


# ---------------------------------------------------------------------------
# Graceful degradation: sections without data don't break the render
# ---------------------------------------------------------------------------

class TestGracefulDegradation:

    def test_missing_evidence_skips_section_07(self):
        """Fixture has no evidence.entries → section 07 omitted, no crash."""
        out = rendered()
        # Since fixture has no evidence.entries, section 07 should be absent
        # (this will change once the fixture is enriched — test then flips)
        form = load_form()
        has_evidence = bool(form["phase_4_structured_llm"].get("evidence", {}).get("entries"))
        if has_evidence:
            assert "## 07 · Evidence appendix" in out
        else:
            assert "## 07 · Evidence appendix" not in out

    def test_missing_coverage_cells_skips_section_06(self):
        form = load_form()
        out = rendered()
        has_coverage = (
            bool(form["phase_3_computed"].get("coverage_status", {}).get("cells"))
            or bool(form["phase_4_structured_llm"].get("coverage_detail", {}).get("rows"))
        )
        if has_coverage:
            assert "## 06 · Investigation coverage" in out
        else:
            assert "## 06 · Investigation coverage" not in out


# ---------------------------------------------------------------------------
# Section order: all 13 headers appear in the correct sequence
# ---------------------------------------------------------------------------

class TestSectionOrder:

    EXPECTED_HEADERS = [
        "## Catalog metadata",
        "## Verdict",
        "## Trust Scorecard",
        "## 01 · What should I do?",
        "## 02 · What we found",
        "## 02A · Executable file inventory",
        "## 03 · Suspicious code changes",
        "## 04 · Timeline",
        "## 05 · Repo vitals",
        "## 06 · Investigation coverage",
        "## 07 · Evidence appendix",
        "## 08 · How this scan works",
    ]

    def test_all_section_headers_present(self):
        out = rendered()
        for h in self.EXPECTED_HEADERS:
            assert h in out, f"Section header missing: {h!r}"

    def test_section_headers_in_order(self):
        out = rendered()
        positions = []
        for h in self.EXPECTED_HEADERS:
            idx = out.find(h)
            assert idx >= 0, f"Section header not found: {h!r}"
            positions.append((h, idx))
        for i in range(len(positions) - 1):
            assert positions[i][1] < positions[i + 1][1], (
                f"Section out of order: {positions[i][0]!r} should precede {positions[i+1][0]!r}"
            )


# ---------------------------------------------------------------------------
# §02A: Executable file inventory
# ---------------------------------------------------------------------------

class TestExecutableInventory:

    def test_section_header_present(self):
        assert "## 02A · Executable file inventory" in rendered()

    def test_layer1_summary_line_present(self):
        out = rendered()
        assert "### Layer 1 — one-line summary" in out

    def test_layer2_table_row_count(self):
        out = rendered()
        form = load_form()
        layer2 = form["phase_4_structured_llm"]["executable_file_inventory"]["layer2_entries"]
        assert len(layer2) == 13
        # Count table rows under ### Layer 2 section (lines starting with |, excluding header + divider)
        layer2_start = out.find("### Layer 2 — per-file runtime inventory")
        assert layer2_start >= 0
        layer2_block = out[layer2_start:]
        # Find the next ### heading to bound the section
        next_section = layer2_block.find("\n## ", 1)
        if next_section < 0:
            next_section = layer2_block.find("\n### ", 1)
        block = layer2_block[:next_section] if next_section > 0 else layer2_block
        table_rows = [
            line for line in block.splitlines()
            if line.startswith("|") and not line.startswith("| File") and not line.startswith("|---")
        ]
        assert len(table_rows) == 13, f"Expected 13 layer2 rows, got {len(table_rows)}"

    def test_closing_note_present(self):
        out = rendered()
        # Closing note discusses the .exec() hit — look for a structural marker
        assert "**Note on the one `.exec()` hit.**" in out


# ---------------------------------------------------------------------------
# §03: PR sample review — richer format
# ---------------------------------------------------------------------------

class TestPRSampleRich:

    def test_richer_table_header_present(self):
        out = rendered()
        assert "| PR | What it did | Submitted by | Merged by | Reviewed? | Concern |" in out

    def test_eight_pr_rows_rendered(self):
        out = rendered()
        form = load_form()
        rows = form["phase_4_structured_llm"]["pr_sample_review"]["rows"]
        assert len(rows) == 8
        # Count table rows under §03 (lines starting with |, not header or divider)
        section_start = out.find("## 03 · Suspicious code changes")
        section_end = out.find("\n## ", section_start + 1)
        block = out[section_start:section_end] if section_end > 0 else out[section_start:]
        pr_rows = [
            line for line in block.splitlines()
            if line.startswith("|") and not line.startswith("| PR ") and not line.startswith("|---")
        ]
        assert len(pr_rows) == 8, f"Expected 8 PR rows, got {len(pr_rows)}"

    def test_pr_rows_link_to_github(self):
        out = rendered()
        form = load_form()
        for row in form["phase_4_structured_llm"]["pr_sample_review"]["rows"]:
            pr_num = row["number"]
            expected_link = f"https://github.com/pmndrs/zustand/pull/{pr_num}"
            assert expected_link in out, f"PR link missing for #{pr_num}"


# ---------------------------------------------------------------------------
# §04: Timeline intro
# ---------------------------------------------------------------------------

class TestTimelineIntro:

    def test_section_header_present(self):
        assert "## 04 · Timeline" in rendered()

    def test_intro_blockquote_contains_six_beats(self):
        out = rendered()
        section_start = out.find("## 04 · Timeline")
        section_end = out.find("\n## ", section_start + 1)
        block = out[section_start:section_end] if section_end > 0 else out[section_start:]
        # The timeline_intro mentions "Six beats across the library's history"
        assert "Six beats across the library" in block

    def test_six_timeline_event_bullets(self):
        out = rendered()
        form = load_form()
        events = form["phase_4_structured_llm"]["timeline_events"]["entries"]
        assert len(events) == 6
        section_start = out.find("## 04 · Timeline")
        section_end = out.find("\n## ", section_start + 1)
        block = out[section_start:section_end] if section_end > 0 else out[section_start:]
        bullet_lines = [l for l in block.splitlines() if l.startswith("- ")]
        assert len(bullet_lines) == 6, f"Expected 6 timeline bullets, got {len(bullet_lines)}"


# ---------------------------------------------------------------------------
# §05: Repo vitals
# ---------------------------------------------------------------------------

class TestRepoVitals:

    def test_section_header_present(self):
        assert "## 05 · Repo vitals" in rendered()

    def test_table_header_present(self):
        assert "| Metric | Value | Note |" in rendered()

    def test_row_count_is_18(self):
        out = rendered()
        form = load_form()
        assert len(form["phase_4_structured_llm"]["repo_vitals"]["rows"]) == 18
        section_start = out.find("## 05 · Repo vitals")
        section_end = out.find("\n## ", section_start + 1)
        block = out[section_start:section_end] if section_end > 0 else out[section_start:]
        data_rows = [
            line for line in block.splitlines()
            if line.startswith("|") and not line.startswith("| Metric") and not line.startswith("|---")
        ]
        assert len(data_rows) == 18, f"Expected 18 repo vitals rows, got {len(data_rows)}"


# ---------------------------------------------------------------------------
# §06: Investigation coverage
# ---------------------------------------------------------------------------

class TestCoverageSection:

    def test_section_header_present(self):
        assert "## 06 · Investigation coverage" in rendered()

    def test_intro_blockquote_present(self):
        out = rendered()
        section_start = out.find("## 06 · Investigation coverage")
        section_end = out.find("\n## ", section_start + 1)
        block = out[section_start:section_end] if section_end > 0 else out[section_start:]
        assert "> " in block, "Section 06 missing blockquote intro"

    def test_check_result_table_header_present(self):
        assert "| Check | Result |" in rendered()

    def test_monorepo_row_absent_for_zustand(self):
        # zustand is_monorepo: false → row should NOT appear in rendered output
        out = rendered()
        form = load_form()
        monorepo_data = form["phase_4_structured_llm"]["coverage_detail"].get("monorepo", {})
        assert monorepo_data.get("is_monorepo") is False
        # The monorepo-specific row text should not appear
        assert "Monorepo scope" not in out or "not a true monorepo" in out

    def test_pull_request_target_usage_row_present(self):
        out = rendered()
        # Should contain note about zero pull_request_target
        assert "pull_request_target" in out
        assert "0 found across 8 workflows" in out

    def test_gaps_noted_block_with_three_entries(self):
        out = rendered()
        form = load_form()
        gaps = form["phase_4_structured_llm"]["coverage_gaps"]["entries"]
        assert len(gaps) == 3
        section_start = out.find("## 06 · Investigation coverage")
        section_end = out.find("\n## ", section_start + 1)
        block = out[section_start:section_end] if section_end > 0 else out[section_start:]
        assert "**Gaps noted:**" in block
        # Three numbered gap items
        numbered = [l for l in block.splitlines() if re.match(r"^\d+\.", l.strip())]
        assert len(numbered) == 3, f"Expected 3 numbered gaps, got {len(numbered)}"


# ---------------------------------------------------------------------------
# §07: Evidence appendix
# ---------------------------------------------------------------------------

class TestEvidenceAppendix:

    def test_section_header_present(self):
        assert "## 07 · Evidence appendix" in rendered()

    def test_pill_row_with_counts(self):
        out = rendered()
        # ℹ 9 facts · ★ 2 priority
        assert "9 facts" in out
        assert "2 priority" in out

    def test_priority_section_header_present(self):
        assert "### ★ Priority evidence (read first)" in rendered()

    def test_e1_and_e3_under_priority(self):
        out = rendered()
        # E1 and E3 are in priority_evidence.selections
        priority_start = out.find("### ★ Priority evidence (read first)")
        other_start = out.find("### Other evidence")
        assert priority_start >= 0
        assert other_start >= 0
        priority_block = out[priority_start:other_start]
        assert "Evidence 1 —" in priority_block
        assert "Evidence 3 —" in priority_block

    def test_other_evidence_entries_present(self):
        out = rendered()
        other_start = out.find("### Other evidence")
        assert other_start >= 0
        other_block = out[other_start:]
        # E2, E4-E9 should all be under Other evidence
        for n in [2, 4, 5, 6, 7, 8, 9]:
            assert f"Evidence {n} —" in other_block, f"E{n} not found under Other evidence"

    def test_each_evidence_block_has_command_and_result_fences(self):
        out = rendered()
        form = load_form()
        entries = form["phase_4_structured_llm"]["evidence"]["entries"]
        assert len(entries) == 9
        # Each evidence block should have a command fence and a result fence
        # Count triple-backtick fences in the evidence section
        section_start = out.find("## 07 · Evidence appendix")
        section_end = out.find("\n## 08 ·")
        block = out[section_start:section_end] if section_end > 0 else out[section_start:]
        fence_count = block.count("```")
        # 9 entries × 2 fences (open+close) per block × 2 fences (command + result) = 36
        assert fence_count >= 36, f"Expected ≥36 fences for 9 entries, got {fence_count}"

    def test_each_evidence_block_has_classification_italic(self):
        out = rendered()
        section_start = out.find("## 07 · Evidence appendix")
        section_end = out.find("\n## 08 ·")
        block = out[section_start:section_end] if section_end > 0 else out[section_start:]
        classification_lines = [l for l in block.splitlines() if l.startswith("*Classification:")]
        assert len(classification_lines) == 9, (
            f"Expected 9 classification lines, got {len(classification_lines)}"
        )


# ---------------------------------------------------------------------------
# §02: Findings enrichment (meta tables, how-to-fix, duration/date lines)
# ---------------------------------------------------------------------------

class TestFindingsEnriched:

    EXPECTED_META_ROW_COUNTS = {
        "F0": 8,
        "F1": 5,
        "F2": 6,
        "F3": 4,
        "F4": 6,
        "F5": 4,
    }
    FINDINGS_WITH_FIX = {"F0", "F1", "F5"}
    FINDINGS_WITHOUT_FIX = {"F2", "F3", "F4"}

    def _finding_block(self, out, fid, all_findings):
        """Return the text block for a single finding (from its ### header to the next ###/## header)."""
        start_marker = f"### {fid} —"
        start = out.find(start_marker)
        assert start >= 0, f"{fid} header not found"
        # Next finding or section
        end = len(out)
        for other in all_findings:
            if other == fid:
                continue
            idx = out.find(f"### {other} —", start + 1)
            if idx > start:
                end = min(end, idx)
        # Also bound by next ## section
        idx = out.find("\n## ", start + 1)
        if idx > start:
            end = min(end, idx)
        return out[start:end]

    def test_all_findings_have_meta_table(self):
        out = rendered()
        for fid in self.EXPECTED_META_ROW_COUNTS:
            assert f"### {fid} —" in out
            # Meta table header must appear after the finding header
            block_start = out.find(f"### {fid} —")
            block_end = out.find("\n### ", block_start + 1)
            if block_end < 0:
                block_end = out.find("\n## ", block_start + 1)
            block = out[block_start:block_end] if block_end > 0 else out[block_start:]
            assert "| Meta | Value |" in block, f"{fid} missing meta table"

    def test_finding_meta_row_counts(self):
        out = rendered()
        all_fids = list(self.EXPECTED_META_ROW_COUNTS.keys())
        for fid, expected_count in self.EXPECTED_META_ROW_COUNTS.items():
            block = self._finding_block(out, fid, all_fids)
            # Find the meta table within the block
            meta_start = block.find("| Meta | Value |")
            assert meta_start >= 0, f"{fid} has no meta table"
            meta_block = block[meta_start:]
            # Rows: lines starting with | that aren't header or divider
            data_rows = [
                l for l in meta_block.splitlines()
                if l.startswith("|") and not l.startswith("| Meta") and not l.startswith("|---")
            ]
            assert len(data_rows) == expected_count, (
                f"{fid}: expected {expected_count} meta rows, got {len(data_rows)}"
            )

    def test_findings_with_fix_have_how_to_fix_block(self):
        out = rendered()
        all_fids = list(self.EXPECTED_META_ROW_COUNTS.keys())
        for fid in self.FINDINGS_WITH_FIX:
            block = self._finding_block(out, fid, all_fids)
            assert "**How to fix.**" in block, f"{fid} missing 'How to fix.' block"

    def test_findings_without_fix_have_no_how_to_fix_block(self):
        out = rendered()
        all_fids = list(self.EXPECTED_META_ROW_COUNTS.keys())
        for fid in self.FINDINGS_WITHOUT_FIX:
            block = self._finding_block(out, fid, all_fids)
            assert "**How to fix.**" not in block, f"{fid} unexpectedly has 'How to fix.' block"

    def test_each_finding_has_duration_date_action_tuple(self):
        out = rendered()
        form = load_form()
        for f in form["phase_4_structured_llm"]["findings"]["entries"]:
            fid = f["id"]
            duration = f.get("duration_label", "")
            # Each finding should have its duration label in the italic line after the header
            block_start = out.find(f"### {fid} —")
            assert block_start >= 0
            # The italic line appears as *duration · ... · → ...*
            block_snippet = out[block_start:block_start + 600]
            assert f"*{duration} ·" in block_snippet or f"*{duration}" in block_snippet, (
                f"{fid} duration label {duration!r} not found in italic line"
            )


# ---------------------------------------------------------------------------
# Verdict exhibits: grouped <details> blocks
# ---------------------------------------------------------------------------

class TestVerdictExhibits:

    def test_exhibits_header_present(self):
        assert "### Verdict exhibits (grouped for reading speed)" in rendered()

    def test_two_details_blocks_present(self):
        out = rendered()
        form = load_form()
        groups = form["phase_4_structured_llm"]["verdict_exhibits"]["groups"]
        assert len(groups) == 2
        assert out.count("<details>") >= 2

    def test_first_group_governance_gaps(self):
        out = rendered()
        # First group: Governance gaps with 2 items
        assert "Governance gaps" in out
        assert "(2 findings)" in out

    def test_second_group_strong_positive_signals(self):
        out = rendered()
        # Second group: Strong positive signals with 8 items
        assert "Strong positive signals" in out
        assert "(8 findings)" in out


# ---------------------------------------------------------------------------
# §01 lead: pill row + summary blockquote
# ---------------------------------------------------------------------------

class TestSection01Lead:

    def test_pill_row_present(self):
        out = rendered()
        # Pill row from section_leads.section_01.pill_row
        assert "✓ Safe to install today" in out
        assert "⚠ 1 consumer-side mitigation" in out
        assert "3 steps" in out

    def test_summary_blockquote_present(self):
        out = rendered()
        section_start = out.find("## 01 · What should I do?")
        section_end = out.find("\n## ", section_start + 1)
        block = out[section_start:section_end] if section_end > 0 else out[section_start:]
        # Summary should include the fixture's summary text (not a fallback placeholder)
        assert "**Install is safe**" in block


# ---------------------------------------------------------------------------
# Phase 4 — derivation helpers tests (chore/template-side-derivation).
# Verify docs/render_helpers.py produces mechanical table-row content from
# phase_1_raw_capture. Helpers are NOT yet wired into templates here — that's
# commit 2 of Phase 4. This commit only verifies the helpers as pure functions.
# ---------------------------------------------------------------------------

_helpers_spec = importlib.util.spec_from_file_location(
    "render_helpers", REPO_ROOT / "docs" / "render_helpers.py"
)
_helpers = importlib.util.module_from_spec(_helpers_spec)
_helpers_spec.loader.exec_module(_helpers)
derive_repo_vitals = _helpers.derive_repo_vitals
derive_coverage_detail = _helpers.derive_coverage_detail
derive_pr_sample = _helpers.derive_pr_sample


SCAN_BUNDLES_DIR = REPO_ROOT / "docs" / "scan-bundles"


def _bundle(name):
    """Load a V1.2 scan bundle by stem."""
    return json.loads((SCAN_BUNDLES_DIR / f"{name}.json").read_text())


class TestDeriveRepoVitals:
    """derive_repo_vitals(p1) — mechanical {metric, value, note} rows."""

    def test_skills_yields_core_identity_metrics(self):
        p1 = _bundle("skills-b843cb5")["phase_1_raw_capture"]
        rows = derive_repo_vitals(p1)
        metrics = {r["metric"]: r["value"] for r in rows}
        assert metrics["Stars"] == "47,917"
        assert metrics["Forks"] == "3,900"
        assert metrics["License"] == "MIT"
        assert metrics["Created"] == "2026-02-03"
        assert metrics["Default branch"] == "main"
        assert metrics["Primary language"] == "Shell"

    def test_skills_yields_governance_metrics(self):
        p1 = _bundle("skills-b843cb5")["phase_1_raw_capture"]
        rows = derive_repo_vitals(p1)
        metrics = {r["metric"]: r["value"] for r in rows}
        assert metrics["CODEOWNERS"] == "absent"
        assert metrics["SECURITY.md"] == "absent"
        assert metrics["Classic branch protection"] == "none (HTTP 404)"
        assert metrics["Repository rulesets"] == "0"
        assert metrics["Rules on default branch"] == "0"

    def test_ghostty_governance_differs_from_skills(self):
        p1 = _bundle("ghostty-dcc39dc")["phase_1_raw_capture"]
        rows = derive_repo_vitals(p1)
        metrics = {r["metric"]: r["value"] for r in rows}
        assert metrics["CODEOWNERS"] == "present"
        assert int(metrics["Repository rulesets"]) >= 1

    def test_top_contributor_pct_computed(self):
        p1 = _bundle("skills-b843cb5")["phase_1_raw_capture"]
        rows = derive_repo_vitals(p1)
        top = next((r for r in rows if r["metric"] == "Top contributor"), None)
        assert top is not None
        assert "mattpocock" in top["value"]
        assert "87" in top["value"]

    def test_note_field_is_none_for_all_derived_rows(self):
        """Helper produces mechanical data only — no LLM commentary."""
        p1 = _bundle("skills-b843cb5")["phase_1_raw_capture"]
        rows = derive_repo_vitals(p1)
        for r in rows:
            assert r["note"] is None, f"derived row should not have a note: {r}"

    def test_empty_phase_1_does_not_crash(self):
        rows = derive_repo_vitals({})
        assert isinstance(rows, list)

    def test_pr_review_metrics_present_when_sample_nonempty(self):
        p1 = _bundle("kamal-6a31d14")["phase_1_raw_capture"]
        rows = derive_repo_vitals(p1)
        metrics = {r["metric"]: r["value"] for r in rows}
        assert "Formal review rate" in metrics
        assert "Any-review rate" in metrics
        assert "PR sample size" in metrics


class TestDeriveCoverageDetail:
    """derive_coverage_detail(p1) — mechanical {check, result} rows from harness flags."""

    def test_skills_reports_tarball_extracted(self):
        p1 = _bundle("skills-b843cb5")["phase_1_raw_capture"]
        rows = derive_coverage_detail(p1)
        checks = {r["check"]: r["result"] for r in rows}
        assert "Tarball extraction + local grep" in checks
        assert "✅" in checks["Tarball extraction + local grep"]

    def test_skills_ossf_reports_not_indexed(self):
        p1 = _bundle("skills-b843cb5")["phase_1_raw_capture"]
        rows = derive_coverage_detail(p1)
        checks = {r["check"]: r["result"] for r in rows}
        assert "OSSF Scorecard" in checks
        assert "Not indexed" in checks["OSSF Scorecard"]

    def test_quicklook_ossf_indexed(self):
        """QuickLook is one of the 2 OSSF-indexed bundles (score 4.1)."""
        p1 = _bundle("QuickLook-0cda83c")["phase_1_raw_capture"]
        rows = derive_coverage_detail(p1)
        checks = {r["check"]: r["result"] for r in rows}
        assert "OSSF Scorecard" in checks
        assert "✅" in checks["OSSF Scorecard"]
        assert "4.1" in checks["OSSF Scorecard"]

    def test_workflows_count_emitted(self):
        p1 = _bundle("kamal-6a31d14")["phase_1_raw_capture"]
        rows = derive_coverage_detail(p1)
        checks = {r["check"]: r["result"] for r in rows}
        assert "Workflows" in checks

    def test_empty_input_returns_empty_list(self):
        assert derive_coverage_detail({}) == []


class TestDerivePRSample:
    """derive_pr_sample(p1) — mechanical PR sample rows from pr_review.prs."""

    def test_kamal_yields_50_rows(self):
        """kamal has 50 PRs in the harness sample."""
        p1 = _bundle("kamal-6a31d14")["phase_1_raw_capture"]
        rows = derive_pr_sample(p1)
        assert len(rows) == 50

    def test_skills_yields_one_row(self):
        """skills has 1 lifetime merged PR."""
        p1 = _bundle("skills-b843cb5")["phase_1_raw_capture"]
        rows = derive_pr_sample(p1)
        assert len(rows) == 1
        assert rows[0]["number"] == 90
        assert rows[0]["self_merge"] is True

    def test_ghostty_yields_zero_rows(self):
        """ghostty bundle has empty pr_review.prs."""
        p1 = _bundle("ghostty-dcc39dc")["phase_1_raw_capture"]
        rows = derive_pr_sample(p1)
        assert rows == []

    def test_row_shape_matches_template_contract(self):
        p1 = _bundle("kamal-6a31d14")["phase_1_raw_capture"]
        rows = derive_pr_sample(p1)
        required_keys = {"number", "title", "formal_review", "any_review",
                         "self_merge", "security_flagged", "merged_at"}
        for r in rows:
            assert set(r.keys()) == required_keys, f"row shape drift: {r.keys()}"

    def test_any_review_is_bool_not_int(self):
        """Helper normalizes any_review_count (int) → any_review (bool)."""
        p1 = _bundle("kamal-6a31d14")["phase_1_raw_capture"]
        rows = derive_pr_sample(p1)
        for r in rows:
            assert isinstance(r["any_review"], bool)
            assert isinstance(r["self_merge"], bool)

    def test_empty_input_returns_empty_list(self):
        assert derive_pr_sample({}) == []


if __name__ == "__main__":
    import pytest
    sys.exit(pytest.main([__file__, "-v"]))
